Update to wrk flow

diff --git a/.github/workflows/custom-image-ci.yml b/.github/workflows/custom-image-ci.yml
--- a/.github/workflows/custom-image-ci.yml
+++ b/.github/workflows/custom-image-ci.yml
@@ -32,7 +32,6 @@ jobs:
       - name: Compressing the project to the zip file
         run: zip -r webapp.zip .
 
-
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
@@ -57,7 +56,6 @@ jobs:
         run: |
           npm run build
 
-
       - name: Packer init (Initialize Packer)
         working-directory: infra
         run: |
@@ -76,15 +74,15 @@ jobs:
         run: |
           # Run Packer build and capture output
           packer build -machine-readable \
-           -var "app_path=/home/csye6225/my_app" \
-          -var "service_name=${{ secrets.service_name }}" \
-          -var "aws_region=${{ secrets.aws_region_ci }}" \
-          -var "source_ami=${{ secrets.source_ami }}" \
-          -var "ami_name=${{ secrets.ami_name }}" \
-          -var "instance_type=${{ secrets.instance_type }}" \
-          -var "subnet_id=${{ secrets.subnet_id }}" \
-          -var "ssh_username=${{ secrets.ssh_username }}" \
-          aws.pkr.hcl | tee packer.log
+            -var "app_path=/home/csye6225/my_app" \
+            -var "service_name=${{ secrets.service_name }}" \
+            -var "aws_region=${{ secrets.aws_region_ci }}" \
+            -var "source_ami=${{ secrets.source_ami }}" \
+            -var "ami_name=${{ secrets.ami_name }}" \
+            -var "instance_type=${{ secrets.instance_type }}" \
+            -var "subnet_id=${{ secrets.subnet_id }}" \
+            -var "ssh_username=${{ secrets.ssh_username }}" \
+            aws.pkr.hcl | tee packer.log
 
           # Extract the AMI ID from the log file
           AMI_ID=$(awk -F, '/artifact,0,id/ {print $6}' packer.log | cut -d: -f2)
@@ -112,3 +110,141 @@ jobs:
               --launch-permission "Add=[{UserId=${{ secrets.DEMO_ID }}}]" \
               --region "${{ secrets.aws_region_ci }}"
           fi
+
+      - name: Get the Environment
+        id: fetch-environment-vars
+        run: |
+          echo "IS_DEV_ENVIRONMENT=${{ vars.isDevEnvironment }}" >> $GITHUB_ENV
+          echo "IS_DEMO_ENVIRONMENT=${{ vars.isDemoEnvironment }}" >> $GITHUB_ENV
+
+      - name: Set the Environment
+        id: determine-environment
+        run: |
+          if [ "${{ env.IS_DEV_ENVIRONMENT }}" == "true" ] && [ "${{ env.IS_DEMO_ENVIRONMENT }}" == "true" ]; then
+            echo "ENVIRONMENTS=dev,demo" >> $GITHUB_ENV
+          elif [ "${{ env.IS_DEV_ENVIRONMENT }}" == "true" ]; then
+            echo "ENVIRONMENTS=dev" >> $GITHUB_ENV
+          elif [ "${{ env.IS_DEMO_ENVIRONMENT }}" == "true" ]; then
+            echo "ENVIRONMENTS=demo" >> $GITHUB_ENV
+          else
+            echo "Error: No environment provided" >&2
+            exit 1
+          fi
+
+      - name: Configure DEV account AWS credentials
+        if: contains(env.ENVIRONMENTS, 'dev')
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Process dev environment
+        if: ${{ env.ENVIRONMENTS == 'dev' || env.ENVIRONMENTS == 'dev,demo' }}
+        run: |
+          echo "currently running in Dev Environment..."
+          # Add Dev-specific commands here
+
+          echo "Update Launch Template started..."
+          # Update Launch Template
+          aws ec2 create-launch-template-version \
+            --launch-template-name "${{ secrets.LAUNCH_TEMPLATE_NAME }}" \
+            --source-version "\$Latest" \
+            --version-description "Updated with latest AMI ID" \
+            --launch-template-data "{\"ImageId\": \"${{ env.AMI_ID }}\"}"
+          echo "Updated launch template successfully..."
+
+          echo "Modify Launch Template started..."
+          aws ec2 modify-launch-template \
+            --launch-template-name "${{ secrets.LAUNCH_TEMPLATE_NAME }}" \
+            --default-version "\$Latest"
+          echo "Launch template modified successfully..."
+
+          # Start Instance Refresh
+          REFRESH_ID=$(aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name "${{ secrets.AUTOSCALING_GROUP_NAME }}" \
+            --preferences '{"MinHealthyPercentage": 50}' \
+            --query 'InstanceRefreshId' \
+            --output text)
+
+          echo "REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV
+
+          echo "Instance Refresh Started..."
+          sleep 30
+
+          while true; do
+            STATUS=$(aws autoscaling describe-instance-refreshes \
+              --auto-scaling-group-name "${{ secrets.AUTOSCALING_GROUP_NAME }}" \
+              --query "InstanceRefreshes[0].Status" \
+              --output text)
+            echo "Current Status: $STATUS"
+            if [ "$STATUS" == "Successful" ]; then
+              echo "Instance Refresh Completed Successfully!"
+              break
+            elif [ "$STATUS" == "Failed" ]; then
+              echo "Instance Refresh Failed."
+              exit 1
+            else
+              echo "Instance Refresh In Progress... Checking again in 30 seconds."
+              sleep 30
+            fi
+          done
+
+      - name: Configure DEMO account AWS credentials
+        if: ${{ env.ENVIRONMENTS == 'demo' || env.ENVIRONMENTS == 'dev,demo' }}
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Process demo environment
+        if: contains(env.ENVIRONMENTS, 'demo')
+        run: |
+          echo "currently running in Demo Environment..."
+          # Add Demo-specific commands here
+
+          echo "Update Launch Template started..."
+          # Update Launch Template
+          aws ec2 create-launch-template-version \
+            --launch-template-name "${{ secrets.LAUNCH_TEMPLATE_NAME }}" \
+            --source-version "\$Latest" \
+            --version-description "Updated with latest AMI ID" \
+            --launch-template-data "{\"ImageId\": \"${{ env.AMI_ID }}\"}"
+          echo "Updated launch template successfully..."
+
+          echo "Modify Launch Template started..."
+          aws ec2 modify-launch-template \
+            --launch-template-name "${{ secrets.LAUNCH_TEMPLATE_NAME }}" \
+            --default-version "\$Latest"
+          echo "Launch template modified successfully..."
+
+          # Start Instance Refresh
+          REFRESH_ID=$(aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name "${{ secrets.AUTOSCALING_GROUP_NAME }}" \
+            --preferences '{"MinHealthyPercentage": 50}' \
+            --query 'InstanceRefreshId' \
+            --output text)
+
+          echo "REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV
+
+          echo "Instance Refresh Started..."
+          sleep 30
+
+          while true; do
+            STATUS=$(aws autoscaling describe-instance-refreshes \
+              --auto-scaling-group-name "${{ secrets.AUTOSCALING_GROUP_NAME }}" \
+              --query "InstanceRefreshes[0].Status" \
+              --output text)
+            echo "Current Status: $STATUS"
+            if [ "$STATUS" == "Successful" ]; then
+              echo "Instance Refresh Completed Successfully!"
+              break
+            elif [ "$STATUS" == "Failed" ]; then
+              echo "Instance Refresh Failed."
+              exit 1
+            else
+              echo "Instance Refresh In Progress... Checking again in 30 seconds."
+              sleep 30
+            fi
+          done
